version: '3.7'

services:

  redis:
    image: 'bitnami/redis:6.2'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: "postgres:15.1"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=outbox_pattern
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./store/init.sql:/docker-entrypoint-initdb.d/init.sql

  asynqmon:
    image: "hibiken/asynqmon:0.7"
    network_mode: "host"
    ports:
      - "8080:8080"

  mailhog:
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres:
